/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as DashboardUploadRouteImport } from './routes/dashboard.upload'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardLedgerRouteImport } from './routes/dashboard.ledger'
import { Route as DashboardHelpRouteImport } from './routes/dashboard.help'
import { Route as DashboardExpensesRouteImport } from './routes/dashboard.expenses'
import { Route as DashboardDonorsRouteImport } from './routes/dashboard.donors'
import { Route as DashboardDonationsRouteImport } from './routes/dashboard.donations'
import { Route as DashboardComplianceRouteImport } from './routes/dashboard.compliance'
import { Route as DashboardCashRouteImport } from './routes/dashboard.cash'
import { Route as DashboardAssetsRouteImport } from './routes/dashboard.assets'
import { Route as AuthCompleteProfileRouteImport } from './routes/auth.complete-profile'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLedgerRoute = DashboardLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExpensesRoute = DashboardExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDonorsRoute = DashboardDonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDonationsRoute = DashboardDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComplianceRoute = DashboardComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCashRoute = DashboardCashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssetsRoute = DashboardAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/dashboard/cash': typeof DashboardCashRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/donations': typeof DashboardDonationsRoute
  '/dashboard/donors': typeof DashboardDonorsRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/ledger': typeof DashboardLedgerRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/dashboard/cash': typeof DashboardCashRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/donations': typeof DashboardDonationsRoute
  '/dashboard/donors': typeof DashboardDonorsRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/ledger': typeof DashboardLedgerRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/dashboard/assets': typeof DashboardAssetsRoute
  '/dashboard/cash': typeof DashboardCashRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/donations': typeof DashboardDonationsRoute
  '/dashboard/donors': typeof DashboardDonorsRoute
  '/dashboard/expenses': typeof DashboardExpensesRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/ledger': typeof DashboardLedgerRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/auth/complete-profile'
    | '/dashboard/assets'
    | '/dashboard/cash'
    | '/dashboard/compliance'
    | '/dashboard/donations'
    | '/dashboard/donors'
    | '/dashboard/expenses'
    | '/dashboard/help'
    | '/dashboard/ledger'
    | '/dashboard/notifications'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/auth/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/auth/complete-profile'
    | '/dashboard/assets'
    | '/dashboard/cash'
    | '/dashboard/compliance'
    | '/dashboard/donations'
    | '/dashboard/donors'
    | '/dashboard/expenses'
    | '/dashboard/help'
    | '/dashboard/ledger'
    | '/dashboard/notifications'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/auth'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/sitemap.xml'
    | '/auth/callback'
    | '/auth/complete-profile'
    | '/dashboard/assets'
    | '/dashboard/cash'
    | '/dashboard/compliance'
    | '/dashboard/donations'
    | '/dashboard/donors'
    | '/dashboard/expenses'
    | '/dashboard/help'
    | '/dashboard/ledger'
    | '/dashboard/notifications'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/auth/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/upload': {
      id: '/dashboard/upload'
      path: '/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ledger': {
      id: '/dashboard/ledger'
      path: '/ledger'
      fullPath: '/dashboard/ledger'
      preLoaderRoute: typeof DashboardLedgerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/help': {
      id: '/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/expenses': {
      id: '/dashboard/expenses'
      path: '/expenses'
      fullPath: '/dashboard/expenses'
      preLoaderRoute: typeof DashboardExpensesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/donors': {
      id: '/dashboard/donors'
      path: '/donors'
      fullPath: '/dashboard/donors'
      preLoaderRoute: typeof DashboardDonorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/donations': {
      id: '/dashboard/donations'
      path: '/donations'
      fullPath: '/dashboard/donations'
      preLoaderRoute: typeof DashboardDonationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/compliance': {
      id: '/dashboard/compliance'
      path: '/compliance'
      fullPath: '/dashboard/compliance'
      preLoaderRoute: typeof DashboardComplianceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cash': {
      id: '/dashboard/cash'
      path: '/cash'
      fullPath: '/dashboard/cash'
      preLoaderRoute: typeof DashboardCashRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assets': {
      id: '/dashboard/assets'
      path: '/assets'
      fullPath: '/dashboard/assets'
      preLoaderRoute: typeof DashboardAssetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/complete-profile': {
      id: '/auth/complete-profile'
      path: '/complete-profile'
      fullPath: '/auth/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardAssetsRoute: typeof DashboardAssetsRoute
  DashboardCashRoute: typeof DashboardCashRoute
  DashboardComplianceRoute: typeof DashboardComplianceRoute
  DashboardDonationsRoute: typeof DashboardDonationsRoute
  DashboardDonorsRoute: typeof DashboardDonorsRoute
  DashboardExpensesRoute: typeof DashboardExpensesRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardLedgerRoute: typeof DashboardLedgerRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUploadRoute: typeof DashboardUploadRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssetsRoute: DashboardAssetsRoute,
  DashboardCashRoute: DashboardCashRoute,
  DashboardComplianceRoute: DashboardComplianceRoute,
  DashboardDonationsRoute: DashboardDonationsRoute,
  DashboardDonorsRoute: DashboardDonorsRoute,
  DashboardExpensesRoute: DashboardExpensesRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardLedgerRoute: DashboardLedgerRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUploadRoute: DashboardUploadRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
